# Generated by Django 4.0.2 on 2022-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_books_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
