# Generated by Django 4.0.2 on 2022-02-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_books_id_alter_books_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
