# Generated by Django 4.0.2 on 2022-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_books_author_name_alter_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
